application: runmap-140616
version: v201610012221
runtime: go
api_version: go1

handlers:
- url: /(.*\.(ico|html))$
  static_files: \1
  upload: .*\.(ico|html)$
- url: /.*
  script: _go_app
